# Generated by Django 2.1.2 on 2019-02-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('product', models.CharField(choices=[('engine', 'ENGINE'), ('piston', 'PISTON'), ('wheel', 'WHEEL')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('release_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
