# Generated by Django 2.1.2 on 2019-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('comp_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tender',
            name='product',
            field=models.CharField(choices=[('samsung', 'SAMSUNG'), ('oppo', 'OPPO'), ('vivo', 'VIVO'), ('mi', 'MI'), ('oneplus', 'ONEPLUS')], max_length=20),
        ),
    ]
