# Generated by Django 2.1.2 on 2019-02-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190213_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inwards',
            fields=[
                ('delivery_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('tender_idno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Tender')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('deliver_idno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inwards')),
                ('tender_idno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tender')),
            ],
        ),
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('required_product', models.CharField(max_length=20)),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supply_date', models.DateField()),
                ('apply_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('tender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tender')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendor')),
            ],
        ),
    ]
