# Generated by Django 2.1.2 on 2019-02-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_inwards_payment_quotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('Product_description', models.TextField(max_length=500)),
                ('vendor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Vendor')),
            ],
        ),
    ]
