# Generated by Django 2.1.2 on 2019-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('Area Manager', 'area manager'), ('Analyzer', 'analyzer'), ('Vendor', 'vendor')], default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
