# Generated by Django 2.1.2 on 2019-02-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_approve_vendors_deliverproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='status',
        ),
    ]
