# Generated by Django 2.1.2 on 2019-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_vendor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_id',
            field=models.IntegerField(),
        ),
    ]
