# Generated by Django 2.1.2 on 2019-02-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190217_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotations',
            name='status',
        ),
    ]
