# Generated by Django 2.1.2 on 2019-02-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_quotations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='status',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='tender_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='vendor_id',
            field=models.IntegerField(),
        ),
    ]
