# Generated by Django 2.1.2 on 2019-02-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190217_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_quotations',
            name='apply_date',
        ),
        migrations.RemoveField(
            model_name='admin_quotations',
            name='supply_date',
        ),
    ]
