# Generated by Django 2.1.2 on 2019-02-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190217_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_quotations',
            name='apply_date',
        ),
        migrations.RemoveField(
            model_name='vendor_quotations',
            name='supply_date',
        ),
    ]
