# Generated by Django 2.1.2 on 2019-02-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190217_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_Vendors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('comp_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
