# Generated by Django 2.1.2 on 2019-02-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_manager_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwards',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AlterField(
            model_name='inwards',
            name='tender_idno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tender'),
        ),
    ]
