# Generated by Django 2.1.2 on 2019-02-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190217_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwards',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inwards',
            name='tender_idno',
        ),
        migrations.AlterField(
            model_name='payment',
            name='deliver_idno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DeliverProducts'),
        ),
        migrations.DeleteModel(
            name='Inwards',
        ),
    ]
