# Generated by Django 2.1.2 on 2019-02-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190217_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverproducts',
            name='deliver_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
