# Generated by Django 2.1.2 on 2019-02-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190217_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inwards',
            fields=[
                ('delivery_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('product', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('tender_idno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tender')),
            ],
        ),
    ]
