# Generated by Django 2.1.2 on 2019-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_inwards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
